### ISSUE TITLE
Problem after the Arch update

### ISSUE THREAD

**Issue by Warmuser** [rliang/kwin-dynamic-virtual-desktops#2]
I had installed these extension on my KDE with Arch but after the update it break my DE. I'm not sure enough but I just want to nitfy you these issue, so If you want to try to replicate the problem. I use Antergos 17.9 with the latest updateds and LTS kernel. Pratically Arch Linux. 

PS: I will try also to install these script on Fedora 26.

**Comment by Warmuser** [comment]
Ok, tested on Fedora 26 + the latest updates available. And It works perfectly. :D

**Comment by Warmuser** [comment]
I will try to replicate the issue on a new Antergos installation (the previous was broken).

**Comment by Warmuser** [comment]
Now I tested again on fedora and look what happen: https://www.youtube.com/watch?v=Znq16jhvmmM

**Comment by rliang** [comment]
Hi, I watched your video but I'm still not sure what happened.

Could you list the following:

* Expected behavior
* Actual behavior
* Steps to reproduce

**Comment by Warmuser** [comment]
I installed the your fantastic kwin script and I set the manimum settings of 3 virtual desktops. That's al, no more other modifies.  Anyway If I try to open any widget from the panel, I get the effect on the video.
