### ISSUE TITLE
broken on 5.11.5

### ISSUE THREAD

**Issue by nicman23** [rliang/kwin-dynamic-virtual-desktops#4]
on plasma desktop 5.11.5-1 per arch linux versioning, the kwin scripts ui does not even list your plugin :/

**Comment by renyuneyun** [comment]
I'm on 5.13.3.1 and this plugin is listed correctly.

Are you using the installation method on the repo (README)?

**Comment by nicman23** [comment]
the error was on the kde side, it now works. closing
